// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/apiauditlog"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApiAuditLogUpdate is the builder for updating ApiAuditLog entities.
type ApiAuditLogUpdate struct {
	config
	hooks     []Hook
	mutation  *ApiAuditLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ApiAuditLogUpdate builder.
func (_u *ApiAuditLogUpdate) Where(ps ...predicate.ApiAuditLog) *ApiAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *ApiAuditLogUpdate) SetRequestID(v string) *ApiAuditLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableRequestID(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *ApiAuditLogUpdate) ClearRequestID() *ApiAuditLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetMethod sets the "method" field.
func (_u *ApiAuditLogUpdate) SetMethod(v string) *ApiAuditLogUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableMethod(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *ApiAuditLogUpdate) ClearMethod() *ApiAuditLogUpdate {
	_u.mutation.ClearMethod()
	return _u
}

// SetOperation sets the "operation" field.
func (_u *ApiAuditLogUpdate) SetOperation(v string) *ApiAuditLogUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableOperation(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// ClearOperation clears the value of the "operation" field.
func (_u *ApiAuditLogUpdate) ClearOperation() *ApiAuditLogUpdate {
	_u.mutation.ClearOperation()
	return _u
}

// SetPath sets the "path" field.
func (_u *ApiAuditLogUpdate) SetPath(v string) *ApiAuditLogUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillablePath(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *ApiAuditLogUpdate) ClearPath() *ApiAuditLogUpdate {
	_u.mutation.ClearPath()
	return _u
}

// SetReferer sets the "referer" field.
func (_u *ApiAuditLogUpdate) SetReferer(v string) *ApiAuditLogUpdate {
	_u.mutation.SetReferer(v)
	return _u
}

// SetNillableReferer sets the "referer" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableReferer(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetReferer(*v)
	}
	return _u
}

// ClearReferer clears the value of the "referer" field.
func (_u *ApiAuditLogUpdate) ClearReferer() *ApiAuditLogUpdate {
	_u.mutation.ClearReferer()
	return _u
}

// SetRequestURI sets the "request_uri" field.
func (_u *ApiAuditLogUpdate) SetRequestURI(v string) *ApiAuditLogUpdate {
	_u.mutation.SetRequestURI(v)
	return _u
}

// SetNillableRequestURI sets the "request_uri" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableRequestURI(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetRequestURI(*v)
	}
	return _u
}

// ClearRequestURI clears the value of the "request_uri" field.
func (_u *ApiAuditLogUpdate) ClearRequestURI() *ApiAuditLogUpdate {
	_u.mutation.ClearRequestURI()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *ApiAuditLogUpdate) SetRequestBody(v string) *ApiAuditLogUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableRequestBody(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *ApiAuditLogUpdate) ClearRequestBody() *ApiAuditLogUpdate {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetRequestHeader sets the "request_header" field.
func (_u *ApiAuditLogUpdate) SetRequestHeader(v string) *ApiAuditLogUpdate {
	_u.mutation.SetRequestHeader(v)
	return _u
}

// SetNillableRequestHeader sets the "request_header" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableRequestHeader(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetRequestHeader(*v)
	}
	return _u
}

// ClearRequestHeader clears the value of the "request_header" field.
func (_u *ApiAuditLogUpdate) ClearRequestHeader() *ApiAuditLogUpdate {
	_u.mutation.ClearRequestHeader()
	return _u
}

// SetResponse sets the "response" field.
func (_u *ApiAuditLogUpdate) SetResponse(v string) *ApiAuditLogUpdate {
	_u.mutation.SetResponse(v)
	return _u
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableResponse(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetResponse(*v)
	}
	return _u
}

// ClearResponse clears the value of the "response" field.
func (_u *ApiAuditLogUpdate) ClearResponse() *ApiAuditLogUpdate {
	_u.mutation.ClearResponse()
	return _u
}

// SetCostTime sets the "cost_time" field.
func (_u *ApiAuditLogUpdate) SetCostTime(v float64) *ApiAuditLogUpdate {
	_u.mutation.ResetCostTime()
	_u.mutation.SetCostTime(v)
	return _u
}

// SetNillableCostTime sets the "cost_time" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableCostTime(v *float64) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetCostTime(*v)
	}
	return _u
}

// AddCostTime adds value to the "cost_time" field.
func (_u *ApiAuditLogUpdate) AddCostTime(v float64) *ApiAuditLogUpdate {
	_u.mutation.AddCostTime(v)
	return _u
}

// ClearCostTime clears the value of the "cost_time" field.
func (_u *ApiAuditLogUpdate) ClearCostTime() *ApiAuditLogUpdate {
	_u.mutation.ClearCostTime()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ApiAuditLogUpdate) SetUserID(v uint32) *ApiAuditLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableUserID(v *uint32) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ApiAuditLogUpdate) AddUserID(v int32) *ApiAuditLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ApiAuditLogUpdate) ClearUserID() *ApiAuditLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *ApiAuditLogUpdate) SetUsername(v string) *ApiAuditLogUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableUsername(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *ApiAuditLogUpdate) ClearUsername() *ApiAuditLogUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *ApiAuditLogUpdate) SetClientIP(v string) *ApiAuditLogUpdate {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableClientIP(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *ApiAuditLogUpdate) ClearClientIP() *ApiAuditLogUpdate {
	_u.mutation.ClearClientIP()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *ApiAuditLogUpdate) SetStatusCode(v int32) *ApiAuditLogUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableStatusCode(v *int32) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *ApiAuditLogUpdate) AddStatusCode(v int32) *ApiAuditLogUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *ApiAuditLogUpdate) ClearStatusCode() *ApiAuditLogUpdate {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetReason sets the "reason" field.
func (_u *ApiAuditLogUpdate) SetReason(v string) *ApiAuditLogUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableReason(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *ApiAuditLogUpdate) ClearReason() *ApiAuditLogUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *ApiAuditLogUpdate) SetSuccess(v bool) *ApiAuditLogUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableSuccess(v *bool) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// ClearSuccess clears the value of the "success" field.
func (_u *ApiAuditLogUpdate) ClearSuccess() *ApiAuditLogUpdate {
	_u.mutation.ClearSuccess()
	return _u
}

// SetLocation sets the "location" field.
func (_u *ApiAuditLogUpdate) SetLocation(v string) *ApiAuditLogUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableLocation(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *ApiAuditLogUpdate) ClearLocation() *ApiAuditLogUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *ApiAuditLogUpdate) SetUserAgent(v string) *ApiAuditLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableUserAgent(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *ApiAuditLogUpdate) ClearUserAgent() *ApiAuditLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetBrowserName sets the "browser_name" field.
func (_u *ApiAuditLogUpdate) SetBrowserName(v string) *ApiAuditLogUpdate {
	_u.mutation.SetBrowserName(v)
	return _u
}

// SetNillableBrowserName sets the "browser_name" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableBrowserName(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetBrowserName(*v)
	}
	return _u
}

// ClearBrowserName clears the value of the "browser_name" field.
func (_u *ApiAuditLogUpdate) ClearBrowserName() *ApiAuditLogUpdate {
	_u.mutation.ClearBrowserName()
	return _u
}

// SetBrowserVersion sets the "browser_version" field.
func (_u *ApiAuditLogUpdate) SetBrowserVersion(v string) *ApiAuditLogUpdate {
	_u.mutation.SetBrowserVersion(v)
	return _u
}

// SetNillableBrowserVersion sets the "browser_version" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableBrowserVersion(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetBrowserVersion(*v)
	}
	return _u
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (_u *ApiAuditLogUpdate) ClearBrowserVersion() *ApiAuditLogUpdate {
	_u.mutation.ClearBrowserVersion()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *ApiAuditLogUpdate) SetClientID(v string) *ApiAuditLogUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableClientID(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *ApiAuditLogUpdate) ClearClientID() *ApiAuditLogUpdate {
	_u.mutation.ClearClientID()
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *ApiAuditLogUpdate) SetClientName(v string) *ApiAuditLogUpdate {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableClientName(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// ClearClientName clears the value of the "client_name" field.
func (_u *ApiAuditLogUpdate) ClearClientName() *ApiAuditLogUpdate {
	_u.mutation.ClearClientName()
	return _u
}

// SetOsName sets the "os_name" field.
func (_u *ApiAuditLogUpdate) SetOsName(v string) *ApiAuditLogUpdate {
	_u.mutation.SetOsName(v)
	return _u
}

// SetNillableOsName sets the "os_name" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableOsName(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetOsName(*v)
	}
	return _u
}

// ClearOsName clears the value of the "os_name" field.
func (_u *ApiAuditLogUpdate) ClearOsName() *ApiAuditLogUpdate {
	_u.mutation.ClearOsName()
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *ApiAuditLogUpdate) SetOsVersion(v string) *ApiAuditLogUpdate {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *ApiAuditLogUpdate) SetNillableOsVersion(v *string) *ApiAuditLogUpdate {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// ClearOsVersion clears the value of the "os_version" field.
func (_u *ApiAuditLogUpdate) ClearOsVersion() *ApiAuditLogUpdate {
	_u.mutation.ClearOsVersion()
	return _u
}

// Mutation returns the ApiAuditLogMutation object of the builder.
func (_u *ApiAuditLogUpdate) Mutation() *ApiAuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApiAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApiAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ApiAuditLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ApiAuditLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ApiAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(apiauditlog.Table, apiauditlog.Columns, sqlgraph.NewFieldSpec(apiauditlog.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(apiauditlog.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(apiauditlog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(apiauditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(apiauditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(apiauditlog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(apiauditlog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(apiauditlog.FieldOperation, field.TypeString, value)
	}
	if _u.mutation.OperationCleared() {
		_spec.ClearField(apiauditlog.FieldOperation, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(apiauditlog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(apiauditlog.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Referer(); ok {
		_spec.SetField(apiauditlog.FieldReferer, field.TypeString, value)
	}
	if _u.mutation.RefererCleared() {
		_spec.ClearField(apiauditlog.FieldReferer, field.TypeString)
	}
	if value, ok := _u.mutation.RequestURI(); ok {
		_spec.SetField(apiauditlog.FieldRequestURI, field.TypeString, value)
	}
	if _u.mutation.RequestURICleared() {
		_spec.ClearField(apiauditlog.FieldRequestURI, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(apiauditlog.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(apiauditlog.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.RequestHeader(); ok {
		_spec.SetField(apiauditlog.FieldRequestHeader, field.TypeString, value)
	}
	if _u.mutation.RequestHeaderCleared() {
		_spec.ClearField(apiauditlog.FieldRequestHeader, field.TypeString)
	}
	if value, ok := _u.mutation.Response(); ok {
		_spec.SetField(apiauditlog.FieldResponse, field.TypeString, value)
	}
	if _u.mutation.ResponseCleared() {
		_spec.ClearField(apiauditlog.FieldResponse, field.TypeString)
	}
	if value, ok := _u.mutation.CostTime(); ok {
		_spec.SetField(apiauditlog.FieldCostTime, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostTime(); ok {
		_spec.AddField(apiauditlog.FieldCostTime, field.TypeFloat64, value)
	}
	if _u.mutation.CostTimeCleared() {
		_spec.ClearField(apiauditlog.FieldCostTime, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(apiauditlog.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(apiauditlog.FieldUserID, field.TypeUint32, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(apiauditlog.FieldUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(apiauditlog.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(apiauditlog.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(apiauditlog.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(apiauditlog.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(apiauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(apiauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(apiauditlog.FieldStatusCode, field.TypeInt32)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(apiauditlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(apiauditlog.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(apiauditlog.FieldSuccess, field.TypeBool, value)
	}
	if _u.mutation.SuccessCleared() {
		_spec.ClearField(apiauditlog.FieldSuccess, field.TypeBool)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(apiauditlog.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(apiauditlog.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(apiauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(apiauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserName(); ok {
		_spec.SetField(apiauditlog.FieldBrowserName, field.TypeString, value)
	}
	if _u.mutation.BrowserNameCleared() {
		_spec.ClearField(apiauditlog.FieldBrowserName, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserVersion(); ok {
		_spec.SetField(apiauditlog.FieldBrowserVersion, field.TypeString, value)
	}
	if _u.mutation.BrowserVersionCleared() {
		_spec.ClearField(apiauditlog.FieldBrowserVersion, field.TypeString)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(apiauditlog.FieldClientID, field.TypeString, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(apiauditlog.FieldClientID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(apiauditlog.FieldClientName, field.TypeString, value)
	}
	if _u.mutation.ClientNameCleared() {
		_spec.ClearField(apiauditlog.FieldClientName, field.TypeString)
	}
	if value, ok := _u.mutation.OsName(); ok {
		_spec.SetField(apiauditlog.FieldOsName, field.TypeString, value)
	}
	if _u.mutation.OsNameCleared() {
		_spec.ClearField(apiauditlog.FieldOsName, field.TypeString)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(apiauditlog.FieldOsVersion, field.TypeString, value)
	}
	if _u.mutation.OsVersionCleared() {
		_spec.ClearField(apiauditlog.FieldOsVersion, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apiauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApiAuditLogUpdateOne is the builder for updating a single ApiAuditLog entity.
type ApiAuditLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ApiAuditLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetRequestID sets the "request_id" field.
func (_u *ApiAuditLogUpdateOne) SetRequestID(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableRequestID(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *ApiAuditLogUpdateOne) ClearRequestID() *ApiAuditLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetMethod sets the "method" field.
func (_u *ApiAuditLogUpdateOne) SetMethod(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableMethod(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *ApiAuditLogUpdateOne) ClearMethod() *ApiAuditLogUpdateOne {
	_u.mutation.ClearMethod()
	return _u
}

// SetOperation sets the "operation" field.
func (_u *ApiAuditLogUpdateOne) SetOperation(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableOperation(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// ClearOperation clears the value of the "operation" field.
func (_u *ApiAuditLogUpdateOne) ClearOperation() *ApiAuditLogUpdateOne {
	_u.mutation.ClearOperation()
	return _u
}

// SetPath sets the "path" field.
func (_u *ApiAuditLogUpdateOne) SetPath(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillablePath(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *ApiAuditLogUpdateOne) ClearPath() *ApiAuditLogUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// SetReferer sets the "referer" field.
func (_u *ApiAuditLogUpdateOne) SetReferer(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetReferer(v)
	return _u
}

// SetNillableReferer sets the "referer" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableReferer(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetReferer(*v)
	}
	return _u
}

// ClearReferer clears the value of the "referer" field.
func (_u *ApiAuditLogUpdateOne) ClearReferer() *ApiAuditLogUpdateOne {
	_u.mutation.ClearReferer()
	return _u
}

// SetRequestURI sets the "request_uri" field.
func (_u *ApiAuditLogUpdateOne) SetRequestURI(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetRequestURI(v)
	return _u
}

// SetNillableRequestURI sets the "request_uri" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableRequestURI(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestURI(*v)
	}
	return _u
}

// ClearRequestURI clears the value of the "request_uri" field.
func (_u *ApiAuditLogUpdateOne) ClearRequestURI() *ApiAuditLogUpdateOne {
	_u.mutation.ClearRequestURI()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *ApiAuditLogUpdateOne) SetRequestBody(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableRequestBody(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *ApiAuditLogUpdateOne) ClearRequestBody() *ApiAuditLogUpdateOne {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetRequestHeader sets the "request_header" field.
func (_u *ApiAuditLogUpdateOne) SetRequestHeader(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetRequestHeader(v)
	return _u
}

// SetNillableRequestHeader sets the "request_header" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableRequestHeader(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestHeader(*v)
	}
	return _u
}

// ClearRequestHeader clears the value of the "request_header" field.
func (_u *ApiAuditLogUpdateOne) ClearRequestHeader() *ApiAuditLogUpdateOne {
	_u.mutation.ClearRequestHeader()
	return _u
}

// SetResponse sets the "response" field.
func (_u *ApiAuditLogUpdateOne) SetResponse(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetResponse(v)
	return _u
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableResponse(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetResponse(*v)
	}
	return _u
}

// ClearResponse clears the value of the "response" field.
func (_u *ApiAuditLogUpdateOne) ClearResponse() *ApiAuditLogUpdateOne {
	_u.mutation.ClearResponse()
	return _u
}

// SetCostTime sets the "cost_time" field.
func (_u *ApiAuditLogUpdateOne) SetCostTime(v float64) *ApiAuditLogUpdateOne {
	_u.mutation.ResetCostTime()
	_u.mutation.SetCostTime(v)
	return _u
}

// SetNillableCostTime sets the "cost_time" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableCostTime(v *float64) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetCostTime(*v)
	}
	return _u
}

// AddCostTime adds value to the "cost_time" field.
func (_u *ApiAuditLogUpdateOne) AddCostTime(v float64) *ApiAuditLogUpdateOne {
	_u.mutation.AddCostTime(v)
	return _u
}

// ClearCostTime clears the value of the "cost_time" field.
func (_u *ApiAuditLogUpdateOne) ClearCostTime() *ApiAuditLogUpdateOne {
	_u.mutation.ClearCostTime()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ApiAuditLogUpdateOne) SetUserID(v uint32) *ApiAuditLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableUserID(v *uint32) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ApiAuditLogUpdateOne) AddUserID(v int32) *ApiAuditLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ApiAuditLogUpdateOne) ClearUserID() *ApiAuditLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *ApiAuditLogUpdateOne) SetUsername(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableUsername(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *ApiAuditLogUpdateOne) ClearUsername() *ApiAuditLogUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *ApiAuditLogUpdateOne) SetClientIP(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableClientIP(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *ApiAuditLogUpdateOne) ClearClientIP() *ApiAuditLogUpdateOne {
	_u.mutation.ClearClientIP()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *ApiAuditLogUpdateOne) SetStatusCode(v int32) *ApiAuditLogUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableStatusCode(v *int32) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *ApiAuditLogUpdateOne) AddStatusCode(v int32) *ApiAuditLogUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *ApiAuditLogUpdateOne) ClearStatusCode() *ApiAuditLogUpdateOne {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetReason sets the "reason" field.
func (_u *ApiAuditLogUpdateOne) SetReason(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableReason(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *ApiAuditLogUpdateOne) ClearReason() *ApiAuditLogUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *ApiAuditLogUpdateOne) SetSuccess(v bool) *ApiAuditLogUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableSuccess(v *bool) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// ClearSuccess clears the value of the "success" field.
func (_u *ApiAuditLogUpdateOne) ClearSuccess() *ApiAuditLogUpdateOne {
	_u.mutation.ClearSuccess()
	return _u
}

// SetLocation sets the "location" field.
func (_u *ApiAuditLogUpdateOne) SetLocation(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableLocation(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *ApiAuditLogUpdateOne) ClearLocation() *ApiAuditLogUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *ApiAuditLogUpdateOne) SetUserAgent(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableUserAgent(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *ApiAuditLogUpdateOne) ClearUserAgent() *ApiAuditLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetBrowserName sets the "browser_name" field.
func (_u *ApiAuditLogUpdateOne) SetBrowserName(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetBrowserName(v)
	return _u
}

// SetNillableBrowserName sets the "browser_name" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableBrowserName(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetBrowserName(*v)
	}
	return _u
}

// ClearBrowserName clears the value of the "browser_name" field.
func (_u *ApiAuditLogUpdateOne) ClearBrowserName() *ApiAuditLogUpdateOne {
	_u.mutation.ClearBrowserName()
	return _u
}

// SetBrowserVersion sets the "browser_version" field.
func (_u *ApiAuditLogUpdateOne) SetBrowserVersion(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetBrowserVersion(v)
	return _u
}

// SetNillableBrowserVersion sets the "browser_version" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableBrowserVersion(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetBrowserVersion(*v)
	}
	return _u
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (_u *ApiAuditLogUpdateOne) ClearBrowserVersion() *ApiAuditLogUpdateOne {
	_u.mutation.ClearBrowserVersion()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *ApiAuditLogUpdateOne) SetClientID(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableClientID(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *ApiAuditLogUpdateOne) ClearClientID() *ApiAuditLogUpdateOne {
	_u.mutation.ClearClientID()
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *ApiAuditLogUpdateOne) SetClientName(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableClientName(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// ClearClientName clears the value of the "client_name" field.
func (_u *ApiAuditLogUpdateOne) ClearClientName() *ApiAuditLogUpdateOne {
	_u.mutation.ClearClientName()
	return _u
}

// SetOsName sets the "os_name" field.
func (_u *ApiAuditLogUpdateOne) SetOsName(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetOsName(v)
	return _u
}

// SetNillableOsName sets the "os_name" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableOsName(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetOsName(*v)
	}
	return _u
}

// ClearOsName clears the value of the "os_name" field.
func (_u *ApiAuditLogUpdateOne) ClearOsName() *ApiAuditLogUpdateOne {
	_u.mutation.ClearOsName()
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *ApiAuditLogUpdateOne) SetOsVersion(v string) *ApiAuditLogUpdateOne {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *ApiAuditLogUpdateOne) SetNillableOsVersion(v *string) *ApiAuditLogUpdateOne {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// ClearOsVersion clears the value of the "os_version" field.
func (_u *ApiAuditLogUpdateOne) ClearOsVersion() *ApiAuditLogUpdateOne {
	_u.mutation.ClearOsVersion()
	return _u
}

// Mutation returns the ApiAuditLogMutation object of the builder.
func (_u *ApiAuditLogUpdateOne) Mutation() *ApiAuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the ApiAuditLogUpdate builder.
func (_u *ApiAuditLogUpdateOne) Where(ps ...predicate.ApiAuditLog) *ApiAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApiAuditLogUpdateOne) Select(field string, fields ...string) *ApiAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApiAuditLog entity.
func (_u *ApiAuditLogUpdateOne) Save(ctx context.Context) (*ApiAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiAuditLogUpdateOne) SaveX(ctx context.Context) *ApiAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApiAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ApiAuditLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ApiAuditLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ApiAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *ApiAuditLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(apiauditlog.Table, apiauditlog.Columns, sqlgraph.NewFieldSpec(apiauditlog.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apiauditlog.FieldID)
		for _, f := range fields {
			if !apiauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apiauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(apiauditlog.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(apiauditlog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(apiauditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(apiauditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(apiauditlog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(apiauditlog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(apiauditlog.FieldOperation, field.TypeString, value)
	}
	if _u.mutation.OperationCleared() {
		_spec.ClearField(apiauditlog.FieldOperation, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(apiauditlog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(apiauditlog.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Referer(); ok {
		_spec.SetField(apiauditlog.FieldReferer, field.TypeString, value)
	}
	if _u.mutation.RefererCleared() {
		_spec.ClearField(apiauditlog.FieldReferer, field.TypeString)
	}
	if value, ok := _u.mutation.RequestURI(); ok {
		_spec.SetField(apiauditlog.FieldRequestURI, field.TypeString, value)
	}
	if _u.mutation.RequestURICleared() {
		_spec.ClearField(apiauditlog.FieldRequestURI, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(apiauditlog.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(apiauditlog.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.RequestHeader(); ok {
		_spec.SetField(apiauditlog.FieldRequestHeader, field.TypeString, value)
	}
	if _u.mutation.RequestHeaderCleared() {
		_spec.ClearField(apiauditlog.FieldRequestHeader, field.TypeString)
	}
	if value, ok := _u.mutation.Response(); ok {
		_spec.SetField(apiauditlog.FieldResponse, field.TypeString, value)
	}
	if _u.mutation.ResponseCleared() {
		_spec.ClearField(apiauditlog.FieldResponse, field.TypeString)
	}
	if value, ok := _u.mutation.CostTime(); ok {
		_spec.SetField(apiauditlog.FieldCostTime, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostTime(); ok {
		_spec.AddField(apiauditlog.FieldCostTime, field.TypeFloat64, value)
	}
	if _u.mutation.CostTimeCleared() {
		_spec.ClearField(apiauditlog.FieldCostTime, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(apiauditlog.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(apiauditlog.FieldUserID, field.TypeUint32, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(apiauditlog.FieldUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(apiauditlog.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(apiauditlog.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(apiauditlog.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(apiauditlog.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(apiauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(apiauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(apiauditlog.FieldStatusCode, field.TypeInt32)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(apiauditlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(apiauditlog.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(apiauditlog.FieldSuccess, field.TypeBool, value)
	}
	if _u.mutation.SuccessCleared() {
		_spec.ClearField(apiauditlog.FieldSuccess, field.TypeBool)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(apiauditlog.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(apiauditlog.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(apiauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(apiauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserName(); ok {
		_spec.SetField(apiauditlog.FieldBrowserName, field.TypeString, value)
	}
	if _u.mutation.BrowserNameCleared() {
		_spec.ClearField(apiauditlog.FieldBrowserName, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserVersion(); ok {
		_spec.SetField(apiauditlog.FieldBrowserVersion, field.TypeString, value)
	}
	if _u.mutation.BrowserVersionCleared() {
		_spec.ClearField(apiauditlog.FieldBrowserVersion, field.TypeString)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(apiauditlog.FieldClientID, field.TypeString, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(apiauditlog.FieldClientID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(apiauditlog.FieldClientName, field.TypeString, value)
	}
	if _u.mutation.ClientNameCleared() {
		_spec.ClearField(apiauditlog.FieldClientName, field.TypeString)
	}
	if value, ok := _u.mutation.OsName(); ok {
		_spec.SetField(apiauditlog.FieldOsName, field.TypeString, value)
	}
	if _u.mutation.OsNameCleared() {
		_spec.ClearField(apiauditlog.FieldOsName, field.TypeString)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(apiauditlog.FieldOsVersion, field.TypeString, value)
	}
	if _u.mutation.OsVersionCleared() {
		_spec.ClearField(apiauditlog.FieldOsVersion, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ApiAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apiauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
