// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/notificationrule"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationRuleCreate is the builder for creating a NotificationRule entity.
type NotificationRuleCreate struct {
	config
	mutation *NotificationRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationRuleCreate) SetCreatedAt(v time.Time) *NotificationRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableCreatedAt(v *time.Time) *NotificationRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationRuleCreate) SetUpdatedAt(v time.Time) *NotificationRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableUpdatedAt(v *time.Time) *NotificationRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *NotificationRuleCreate) SetDeletedAt(v time.Time) *NotificationRuleCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableDeletedAt(v *time.Time) *NotificationRuleCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *NotificationRuleCreate) SetCreatedBy(v uint32) *NotificationRuleCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableCreatedBy(v *uint32) *NotificationRuleCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *NotificationRuleCreate) SetUpdatedBy(v uint32) *NotificationRuleCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableUpdatedBy(v *uint32) *NotificationRuleCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *NotificationRuleCreate) SetDeletedBy(v uint32) *NotificationRuleCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableDeletedBy(v *uint32) *NotificationRuleCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetIsEnabled sets the "is_enabled" field.
func (_c *NotificationRuleCreate) SetIsEnabled(v bool) *NotificationRuleCreate {
	_c.mutation.SetIsEnabled(v)
	return _c
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableIsEnabled(v *bool) *NotificationRuleCreate {
	if v != nil {
		_c.SetIsEnabled(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *NotificationRuleCreate) SetRemark(v string) *NotificationRuleCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableRemark(v *string) *NotificationRuleCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *NotificationRuleCreate) SetEventType(v notificationrule.EventType) *NotificationRuleCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableEventType(v *notificationrule.EventType) *NotificationRuleCreate {
	if v != nil {
		_c.SetEventType(*v)
	}
	return _c
}

// SetChannel sets the "channel" field.
func (_c *NotificationRuleCreate) SetChannel(v notificationrule.Channel) *NotificationRuleCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableChannel(v *notificationrule.Channel) *NotificationRuleCreate {
	if v != nil {
		_c.SetChannel(*v)
	}
	return _c
}

// SetIsAsync sets the "is_async" field.
func (_c *NotificationRuleCreate) SetIsAsync(v bool) *NotificationRuleCreate {
	_c.mutation.SetIsAsync(v)
	return _c
}

// SetNillableIsAsync sets the "is_async" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableIsAsync(v *bool) *NotificationRuleCreate {
	if v != nil {
		_c.SetIsAsync(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationRuleCreate) SetID(v uint32) *NotificationRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NotificationRuleMutation object of the builder.
func (_c *NotificationRuleCreate) Mutation() *NotificationRuleMutation {
	return _c.mutation
}

// Save creates the NotificationRule in the database.
func (_c *NotificationRuleCreate) Save(ctx context.Context) (*NotificationRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationRuleCreate) SaveX(ctx context.Context) *NotificationRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationRuleCreate) defaults() {
	if _, ok := _c.mutation.IsEnabled(); !ok {
		v := notificationrule.DefaultIsEnabled
		_c.mutation.SetIsEnabled(v)
	}
	if _, ok := _c.mutation.IsAsync(); !ok {
		v := notificationrule.DefaultIsAsync
		_c.mutation.SetIsAsync(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationRuleCreate) check() error {
	if v, ok := _c.mutation.EventType(); ok {
		if err := notificationrule.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "NotificationRule.event_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := notificationrule.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "NotificationRule.channel": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := notificationrule.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "NotificationRule.id": %w`, err)}
		}
	}
	return nil
}

func (_c *NotificationRuleCreate) sqlSave(ctx context.Context) (*NotificationRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationRuleCreate) createSpec() (*NotificationRule, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationrule.Table, sqlgraph.NewFieldSpec(notificationrule.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(notificationrule.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(notificationrule.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(notificationrule.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(notificationrule.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.IsEnabled(); ok {
		_spec.SetField(notificationrule.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(notificationrule.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(notificationrule.FieldEventType, field.TypeEnum, value)
		_node.EventType = &value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(notificationrule.FieldChannel, field.TypeEnum, value)
		_node.Channel = &value
	}
	if value, ok := _c.mutation.IsAsync(); ok {
		_spec.SetField(notificationrule.FieldIsAsync, field.TypeBool, value)
		_node.IsAsync = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationRuleCreate) OnConflict(opts ...sql.ConflictOption) *NotificationRuleUpsertOne {
	_c.conflict = opts
	return &NotificationRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationRuleCreate) OnConflictColumns(columns ...string) *NotificationRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationRuleUpsertOne{
		create: _c,
	}
}

type (
	// NotificationRuleUpsertOne is the builder for "upsert"-ing
	//  one NotificationRule node.
	NotificationRuleUpsertOne struct {
		create *NotificationRuleCreate
	}

	// NotificationRuleUpsert is the "OnConflict" setter.
	NotificationRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationRuleUpsert) SetUpdatedAt(v time.Time) *NotificationRuleUpsert {
	u.Set(notificationrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationRuleUpsert) UpdateUpdatedAt() *NotificationRuleUpsert {
	u.SetExcluded(notificationrule.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *NotificationRuleUpsert) ClearUpdatedAt() *NotificationRuleUpsert {
	u.SetNull(notificationrule.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *NotificationRuleUpsert) SetDeletedAt(v time.Time) *NotificationRuleUpsert {
	u.Set(notificationrule.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NotificationRuleUpsert) UpdateDeletedAt() *NotificationRuleUpsert {
	u.SetExcluded(notificationrule.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NotificationRuleUpsert) ClearDeletedAt() *NotificationRuleUpsert {
	u.SetNull(notificationrule.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *NotificationRuleUpsert) SetCreatedBy(v uint32) *NotificationRuleUpsert {
	u.Set(notificationrule.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NotificationRuleUpsert) UpdateCreatedBy() *NotificationRuleUpsert {
	u.SetExcluded(notificationrule.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *NotificationRuleUpsert) AddCreatedBy(v uint32) *NotificationRuleUpsert {
	u.Add(notificationrule.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *NotificationRuleUpsert) ClearCreatedBy() *NotificationRuleUpsert {
	u.SetNull(notificationrule.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *NotificationRuleUpsert) SetUpdatedBy(v uint32) *NotificationRuleUpsert {
	u.Set(notificationrule.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *NotificationRuleUpsert) UpdateUpdatedBy() *NotificationRuleUpsert {
	u.SetExcluded(notificationrule.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *NotificationRuleUpsert) AddUpdatedBy(v uint32) *NotificationRuleUpsert {
	u.Add(notificationrule.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *NotificationRuleUpsert) ClearUpdatedBy() *NotificationRuleUpsert {
	u.SetNull(notificationrule.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *NotificationRuleUpsert) SetDeletedBy(v uint32) *NotificationRuleUpsert {
	u.Set(notificationrule.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *NotificationRuleUpsert) UpdateDeletedBy() *NotificationRuleUpsert {
	u.SetExcluded(notificationrule.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *NotificationRuleUpsert) AddDeletedBy(v uint32) *NotificationRuleUpsert {
	u.Add(notificationrule.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *NotificationRuleUpsert) ClearDeletedBy() *NotificationRuleUpsert {
	u.SetNull(notificationrule.FieldDeletedBy)
	return u
}

// SetIsEnabled sets the "is_enabled" field.
func (u *NotificationRuleUpsert) SetIsEnabled(v bool) *NotificationRuleUpsert {
	u.Set(notificationrule.FieldIsEnabled, v)
	return u
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *NotificationRuleUpsert) UpdateIsEnabled() *NotificationRuleUpsert {
	u.SetExcluded(notificationrule.FieldIsEnabled)
	return u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *NotificationRuleUpsert) ClearIsEnabled() *NotificationRuleUpsert {
	u.SetNull(notificationrule.FieldIsEnabled)
	return u
}

// SetRemark sets the "remark" field.
func (u *NotificationRuleUpsert) SetRemark(v string) *NotificationRuleUpsert {
	u.Set(notificationrule.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *NotificationRuleUpsert) UpdateRemark() *NotificationRuleUpsert {
	u.SetExcluded(notificationrule.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *NotificationRuleUpsert) ClearRemark() *NotificationRuleUpsert {
	u.SetNull(notificationrule.FieldRemark)
	return u
}

// SetEventType sets the "event_type" field.
func (u *NotificationRuleUpsert) SetEventType(v notificationrule.EventType) *NotificationRuleUpsert {
	u.Set(notificationrule.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *NotificationRuleUpsert) UpdateEventType() *NotificationRuleUpsert {
	u.SetExcluded(notificationrule.FieldEventType)
	return u
}

// ClearEventType clears the value of the "event_type" field.
func (u *NotificationRuleUpsert) ClearEventType() *NotificationRuleUpsert {
	u.SetNull(notificationrule.FieldEventType)
	return u
}

// SetChannel sets the "channel" field.
func (u *NotificationRuleUpsert) SetChannel(v notificationrule.Channel) *NotificationRuleUpsert {
	u.Set(notificationrule.FieldChannel, v)
	return u
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *NotificationRuleUpsert) UpdateChannel() *NotificationRuleUpsert {
	u.SetExcluded(notificationrule.FieldChannel)
	return u
}

// ClearChannel clears the value of the "channel" field.
func (u *NotificationRuleUpsert) ClearChannel() *NotificationRuleUpsert {
	u.SetNull(notificationrule.FieldChannel)
	return u
}

// SetIsAsync sets the "is_async" field.
func (u *NotificationRuleUpsert) SetIsAsync(v bool) *NotificationRuleUpsert {
	u.Set(notificationrule.FieldIsAsync, v)
	return u
}

// UpdateIsAsync sets the "is_async" field to the value that was provided on create.
func (u *NotificationRuleUpsert) UpdateIsAsync() *NotificationRuleUpsert {
	u.SetExcluded(notificationrule.FieldIsAsync)
	return u
}

// ClearIsAsync clears the value of the "is_async" field.
func (u *NotificationRuleUpsert) ClearIsAsync() *NotificationRuleUpsert {
	u.SetNull(notificationrule.FieldIsAsync)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NotificationRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationRuleUpsertOne) UpdateNewValues() *NotificationRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(notificationrule.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(notificationrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationRuleUpsertOne) Ignore() *NotificationRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationRuleUpsertOne) DoNothing() *NotificationRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationRuleCreate.OnConflict
// documentation for more info.
func (u *NotificationRuleUpsertOne) Update(set func(*NotificationRuleUpsert)) *NotificationRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationRuleUpsertOne) SetUpdatedAt(v time.Time) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationRuleUpsertOne) UpdateUpdatedAt() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *NotificationRuleUpsertOne) ClearUpdatedAt() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *NotificationRuleUpsertOne) SetDeletedAt(v time.Time) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NotificationRuleUpsertOne) UpdateDeletedAt() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NotificationRuleUpsertOne) ClearDeletedAt() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *NotificationRuleUpsertOne) SetCreatedBy(v uint32) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *NotificationRuleUpsertOne) AddCreatedBy(v uint32) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NotificationRuleUpsertOne) UpdateCreatedBy() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *NotificationRuleUpsertOne) ClearCreatedBy() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *NotificationRuleUpsertOne) SetUpdatedBy(v uint32) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *NotificationRuleUpsertOne) AddUpdatedBy(v uint32) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *NotificationRuleUpsertOne) UpdateUpdatedBy() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *NotificationRuleUpsertOne) ClearUpdatedBy() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *NotificationRuleUpsertOne) SetDeletedBy(v uint32) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *NotificationRuleUpsertOne) AddDeletedBy(v uint32) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *NotificationRuleUpsertOne) UpdateDeletedBy() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *NotificationRuleUpsertOne) ClearDeletedBy() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearDeletedBy()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *NotificationRuleUpsertOne) SetIsEnabled(v bool) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *NotificationRuleUpsertOne) UpdateIsEnabled() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateIsEnabled()
	})
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *NotificationRuleUpsertOne) ClearIsEnabled() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearIsEnabled()
	})
}

// SetRemark sets the "remark" field.
func (u *NotificationRuleUpsertOne) SetRemark(v string) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *NotificationRuleUpsertOne) UpdateRemark() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *NotificationRuleUpsertOne) ClearRemark() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearRemark()
	})
}

// SetEventType sets the "event_type" field.
func (u *NotificationRuleUpsertOne) SetEventType(v notificationrule.EventType) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *NotificationRuleUpsertOne) UpdateEventType() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateEventType()
	})
}

// ClearEventType clears the value of the "event_type" field.
func (u *NotificationRuleUpsertOne) ClearEventType() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearEventType()
	})
}

// SetChannel sets the "channel" field.
func (u *NotificationRuleUpsertOne) SetChannel(v notificationrule.Channel) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *NotificationRuleUpsertOne) UpdateChannel() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateChannel()
	})
}

// ClearChannel clears the value of the "channel" field.
func (u *NotificationRuleUpsertOne) ClearChannel() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearChannel()
	})
}

// SetIsAsync sets the "is_async" field.
func (u *NotificationRuleUpsertOne) SetIsAsync(v bool) *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetIsAsync(v)
	})
}

// UpdateIsAsync sets the "is_async" field to the value that was provided on create.
func (u *NotificationRuleUpsertOne) UpdateIsAsync() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateIsAsync()
	})
}

// ClearIsAsync clears the value of the "is_async" field.
func (u *NotificationRuleUpsertOne) ClearIsAsync() *NotificationRuleUpsertOne {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearIsAsync()
	})
}

// Exec executes the query.
func (u *NotificationRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationRuleUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationRuleUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationRuleCreateBulk is the builder for creating many NotificationRule entities in bulk.
type NotificationRuleCreateBulk struct {
	config
	err      error
	builders []*NotificationRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the NotificationRule entities in the database.
func (_c *NotificationRuleCreateBulk) Save(ctx context.Context) ([]*NotificationRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationRuleCreateBulk) SaveX(ctx context.Context) []*NotificationRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationRuleUpsertBulk {
	_c.conflict = opts
	return &NotificationRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationRuleCreateBulk) OnConflictColumns(columns ...string) *NotificationRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationRuleUpsertBulk{
		create: _c,
	}
}

// NotificationRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of NotificationRule nodes.
type NotificationRuleUpsertBulk struct {
	create *NotificationRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotificationRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationRuleUpsertBulk) UpdateNewValues() *NotificationRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(notificationrule.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(notificationrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationRuleUpsertBulk) Ignore() *NotificationRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationRuleUpsertBulk) DoNothing() *NotificationRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationRuleCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationRuleUpsertBulk) Update(set func(*NotificationRuleUpsert)) *NotificationRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationRuleUpsertBulk) SetUpdatedAt(v time.Time) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationRuleUpsertBulk) UpdateUpdatedAt() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *NotificationRuleUpsertBulk) ClearUpdatedAt() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *NotificationRuleUpsertBulk) SetDeletedAt(v time.Time) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NotificationRuleUpsertBulk) UpdateDeletedAt() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NotificationRuleUpsertBulk) ClearDeletedAt() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *NotificationRuleUpsertBulk) SetCreatedBy(v uint32) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *NotificationRuleUpsertBulk) AddCreatedBy(v uint32) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NotificationRuleUpsertBulk) UpdateCreatedBy() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *NotificationRuleUpsertBulk) ClearCreatedBy() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *NotificationRuleUpsertBulk) SetUpdatedBy(v uint32) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *NotificationRuleUpsertBulk) AddUpdatedBy(v uint32) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *NotificationRuleUpsertBulk) UpdateUpdatedBy() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *NotificationRuleUpsertBulk) ClearUpdatedBy() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *NotificationRuleUpsertBulk) SetDeletedBy(v uint32) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *NotificationRuleUpsertBulk) AddDeletedBy(v uint32) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *NotificationRuleUpsertBulk) UpdateDeletedBy() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *NotificationRuleUpsertBulk) ClearDeletedBy() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearDeletedBy()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *NotificationRuleUpsertBulk) SetIsEnabled(v bool) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *NotificationRuleUpsertBulk) UpdateIsEnabled() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateIsEnabled()
	})
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *NotificationRuleUpsertBulk) ClearIsEnabled() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearIsEnabled()
	})
}

// SetRemark sets the "remark" field.
func (u *NotificationRuleUpsertBulk) SetRemark(v string) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *NotificationRuleUpsertBulk) UpdateRemark() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *NotificationRuleUpsertBulk) ClearRemark() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearRemark()
	})
}

// SetEventType sets the "event_type" field.
func (u *NotificationRuleUpsertBulk) SetEventType(v notificationrule.EventType) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *NotificationRuleUpsertBulk) UpdateEventType() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateEventType()
	})
}

// ClearEventType clears the value of the "event_type" field.
func (u *NotificationRuleUpsertBulk) ClearEventType() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearEventType()
	})
}

// SetChannel sets the "channel" field.
func (u *NotificationRuleUpsertBulk) SetChannel(v notificationrule.Channel) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *NotificationRuleUpsertBulk) UpdateChannel() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateChannel()
	})
}

// ClearChannel clears the value of the "channel" field.
func (u *NotificationRuleUpsertBulk) ClearChannel() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearChannel()
	})
}

// SetIsAsync sets the "is_async" field.
func (u *NotificationRuleUpsertBulk) SetIsAsync(v bool) *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.SetIsAsync(v)
	})
}

// UpdateIsAsync sets the "is_async" field to the value that was provided on create.
func (u *NotificationRuleUpsertBulk) UpdateIsAsync() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.UpdateIsAsync()
	})
}

// ClearIsAsync clears the value of the "is_async" field.
func (u *NotificationRuleUpsertBulk) ClearIsAsync() *NotificationRuleUpsertBulk {
	return u.Update(func(s *NotificationRuleUpsert) {
		s.ClearIsAsync()
	})
}

// Exec executes the query.
func (u *NotificationRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
