// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/permissionapiresource"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PermissionApiResourceCreate is the builder for creating a PermissionApiResource entity.
type PermissionApiResourceCreate struct {
	config
	mutation *PermissionApiResourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PermissionApiResourceCreate) SetCreatedAt(v time.Time) *PermissionApiResourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PermissionApiResourceCreate) SetNillableCreatedAt(v *time.Time) *PermissionApiResourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PermissionApiResourceCreate) SetUpdatedAt(v time.Time) *PermissionApiResourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PermissionApiResourceCreate) SetNillableUpdatedAt(v *time.Time) *PermissionApiResourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PermissionApiResourceCreate) SetDeletedAt(v time.Time) *PermissionApiResourceCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PermissionApiResourceCreate) SetNillableDeletedAt(v *time.Time) *PermissionApiResourceCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PermissionApiResourceCreate) SetCreatedBy(v uint32) *PermissionApiResourceCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *PermissionApiResourceCreate) SetNillableCreatedBy(v *uint32) *PermissionApiResourceCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *PermissionApiResourceCreate) SetUpdatedBy(v uint32) *PermissionApiResourceCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *PermissionApiResourceCreate) SetNillableUpdatedBy(v *uint32) *PermissionApiResourceCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *PermissionApiResourceCreate) SetDeletedBy(v uint32) *PermissionApiResourceCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *PermissionApiResourceCreate) SetNillableDeletedBy(v *uint32) *PermissionApiResourceCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *PermissionApiResourceCreate) SetTenantID(v uint32) *PermissionApiResourceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *PermissionApiResourceCreate) SetNillableTenantID(v *uint32) *PermissionApiResourceCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetPermissionID sets the "permission_id" field.
func (_c *PermissionApiResourceCreate) SetPermissionID(v uint32) *PermissionApiResourceCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetAPIResourceID sets the "api_resource_id" field.
func (_c *PermissionApiResourceCreate) SetAPIResourceID(v uint32) *PermissionApiResourceCreate {
	_c.mutation.SetAPIResourceID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PermissionApiResourceCreate) SetID(v uint32) *PermissionApiResourceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PermissionApiResourceMutation object of the builder.
func (_c *PermissionApiResourceCreate) Mutation() *PermissionApiResourceMutation {
	return _c.mutation
}

// Save creates the PermissionApiResource in the database.
func (_c *PermissionApiResourceCreate) Save(ctx context.Context) (*PermissionApiResource, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PermissionApiResourceCreate) SaveX(ctx context.Context) *PermissionApiResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionApiResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionApiResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PermissionApiResourceCreate) check() error {
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "PermissionApiResource.permission_id"`)}
	}
	if _, ok := _c.mutation.APIResourceID(); !ok {
		return &ValidationError{Name: "api_resource_id", err: errors.New(`ent: missing required field "PermissionApiResource.api_resource_id"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := permissionapiresource.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PermissionApiResource.id": %w`, err)}
		}
	}
	return nil
}

func (_c *PermissionApiResourceCreate) sqlSave(ctx context.Context) (*PermissionApiResource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PermissionApiResourceCreate) createSpec() (*PermissionApiResource, *sqlgraph.CreateSpec) {
	var (
		_node = &PermissionApiResource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(permissionapiresource.Table, sqlgraph.NewFieldSpec(permissionapiresource.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(permissionapiresource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(permissionapiresource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(permissionapiresource.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(permissionapiresource.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(permissionapiresource.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(permissionapiresource.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(permissionapiresource.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.PermissionID(); ok {
		_spec.SetField(permissionapiresource.FieldPermissionID, field.TypeUint32, value)
		_node.PermissionID = &value
	}
	if value, ok := _c.mutation.APIResourceID(); ok {
		_spec.SetField(permissionapiresource.FieldAPIResourceID, field.TypeUint32, value)
		_node.APIResourceID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PermissionApiResource.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PermissionApiResourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PermissionApiResourceCreate) OnConflict(opts ...sql.ConflictOption) *PermissionApiResourceUpsertOne {
	_c.conflict = opts
	return &PermissionApiResourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PermissionApiResource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PermissionApiResourceCreate) OnConflictColumns(columns ...string) *PermissionApiResourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PermissionApiResourceUpsertOne{
		create: _c,
	}
}

type (
	// PermissionApiResourceUpsertOne is the builder for "upsert"-ing
	//  one PermissionApiResource node.
	PermissionApiResourceUpsertOne struct {
		create *PermissionApiResourceCreate
	}

	// PermissionApiResourceUpsert is the "OnConflict" setter.
	PermissionApiResourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PermissionApiResourceUpsert) SetUpdatedAt(v time.Time) *PermissionApiResourceUpsert {
	u.Set(permissionapiresource.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PermissionApiResourceUpsert) UpdateUpdatedAt() *PermissionApiResourceUpsert {
	u.SetExcluded(permissionapiresource.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PermissionApiResourceUpsert) ClearUpdatedAt() *PermissionApiResourceUpsert {
	u.SetNull(permissionapiresource.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PermissionApiResourceUpsert) SetDeletedAt(v time.Time) *PermissionApiResourceUpsert {
	u.Set(permissionapiresource.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PermissionApiResourceUpsert) UpdateDeletedAt() *PermissionApiResourceUpsert {
	u.SetExcluded(permissionapiresource.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PermissionApiResourceUpsert) ClearDeletedAt() *PermissionApiResourceUpsert {
	u.SetNull(permissionapiresource.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *PermissionApiResourceUpsert) SetCreatedBy(v uint32) *PermissionApiResourceUpsert {
	u.Set(permissionapiresource.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PermissionApiResourceUpsert) UpdateCreatedBy() *PermissionApiResourceUpsert {
	u.SetExcluded(permissionapiresource.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PermissionApiResourceUpsert) AddCreatedBy(v uint32) *PermissionApiResourceUpsert {
	u.Add(permissionapiresource.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PermissionApiResourceUpsert) ClearCreatedBy() *PermissionApiResourceUpsert {
	u.SetNull(permissionapiresource.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PermissionApiResourceUpsert) SetUpdatedBy(v uint32) *PermissionApiResourceUpsert {
	u.Set(permissionapiresource.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PermissionApiResourceUpsert) UpdateUpdatedBy() *PermissionApiResourceUpsert {
	u.SetExcluded(permissionapiresource.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PermissionApiResourceUpsert) AddUpdatedBy(v uint32) *PermissionApiResourceUpsert {
	u.Add(permissionapiresource.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PermissionApiResourceUpsert) ClearUpdatedBy() *PermissionApiResourceUpsert {
	u.SetNull(permissionapiresource.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PermissionApiResourceUpsert) SetDeletedBy(v uint32) *PermissionApiResourceUpsert {
	u.Set(permissionapiresource.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PermissionApiResourceUpsert) UpdateDeletedBy() *PermissionApiResourceUpsert {
	u.SetExcluded(permissionapiresource.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PermissionApiResourceUpsert) AddDeletedBy(v uint32) *PermissionApiResourceUpsert {
	u.Add(permissionapiresource.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PermissionApiResourceUpsert) ClearDeletedBy() *PermissionApiResourceUpsert {
	u.SetNull(permissionapiresource.FieldDeletedBy)
	return u
}

// SetPermissionID sets the "permission_id" field.
func (u *PermissionApiResourceUpsert) SetPermissionID(v uint32) *PermissionApiResourceUpsert {
	u.Set(permissionapiresource.FieldPermissionID, v)
	return u
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *PermissionApiResourceUpsert) UpdatePermissionID() *PermissionApiResourceUpsert {
	u.SetExcluded(permissionapiresource.FieldPermissionID)
	return u
}

// AddPermissionID adds v to the "permission_id" field.
func (u *PermissionApiResourceUpsert) AddPermissionID(v uint32) *PermissionApiResourceUpsert {
	u.Add(permissionapiresource.FieldPermissionID, v)
	return u
}

// SetAPIResourceID sets the "api_resource_id" field.
func (u *PermissionApiResourceUpsert) SetAPIResourceID(v uint32) *PermissionApiResourceUpsert {
	u.Set(permissionapiresource.FieldAPIResourceID, v)
	return u
}

// UpdateAPIResourceID sets the "api_resource_id" field to the value that was provided on create.
func (u *PermissionApiResourceUpsert) UpdateAPIResourceID() *PermissionApiResourceUpsert {
	u.SetExcluded(permissionapiresource.FieldAPIResourceID)
	return u
}

// AddAPIResourceID adds v to the "api_resource_id" field.
func (u *PermissionApiResourceUpsert) AddAPIResourceID(v uint32) *PermissionApiResourceUpsert {
	u.Add(permissionapiresource.FieldAPIResourceID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PermissionApiResource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(permissionapiresource.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PermissionApiResourceUpsertOne) UpdateNewValues() *PermissionApiResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(permissionapiresource.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(permissionapiresource.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(permissionapiresource.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PermissionApiResource.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PermissionApiResourceUpsertOne) Ignore() *PermissionApiResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PermissionApiResourceUpsertOne) DoNothing() *PermissionApiResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PermissionApiResourceCreate.OnConflict
// documentation for more info.
func (u *PermissionApiResourceUpsertOne) Update(set func(*PermissionApiResourceUpsert)) *PermissionApiResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PermissionApiResourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PermissionApiResourceUpsertOne) SetUpdatedAt(v time.Time) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertOne) UpdateUpdatedAt() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PermissionApiResourceUpsertOne) ClearUpdatedAt() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PermissionApiResourceUpsertOne) SetDeletedAt(v time.Time) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertOne) UpdateDeletedAt() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PermissionApiResourceUpsertOne) ClearDeletedAt() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *PermissionApiResourceUpsertOne) SetCreatedBy(v uint32) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PermissionApiResourceUpsertOne) AddCreatedBy(v uint32) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertOne) UpdateCreatedBy() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PermissionApiResourceUpsertOne) ClearCreatedBy() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PermissionApiResourceUpsertOne) SetUpdatedBy(v uint32) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PermissionApiResourceUpsertOne) AddUpdatedBy(v uint32) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertOne) UpdateUpdatedBy() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PermissionApiResourceUpsertOne) ClearUpdatedBy() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PermissionApiResourceUpsertOne) SetDeletedBy(v uint32) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PermissionApiResourceUpsertOne) AddDeletedBy(v uint32) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertOne) UpdateDeletedBy() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PermissionApiResourceUpsertOne) ClearDeletedBy() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.ClearDeletedBy()
	})
}

// SetPermissionID sets the "permission_id" field.
func (u *PermissionApiResourceUpsertOne) SetPermissionID(v uint32) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetPermissionID(v)
	})
}

// AddPermissionID adds v to the "permission_id" field.
func (u *PermissionApiResourceUpsertOne) AddPermissionID(v uint32) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.AddPermissionID(v)
	})
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertOne) UpdatePermissionID() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdatePermissionID()
	})
}

// SetAPIResourceID sets the "api_resource_id" field.
func (u *PermissionApiResourceUpsertOne) SetAPIResourceID(v uint32) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetAPIResourceID(v)
	})
}

// AddAPIResourceID adds v to the "api_resource_id" field.
func (u *PermissionApiResourceUpsertOne) AddAPIResourceID(v uint32) *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.AddAPIResourceID(v)
	})
}

// UpdateAPIResourceID sets the "api_resource_id" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertOne) UpdateAPIResourceID() *PermissionApiResourceUpsertOne {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateAPIResourceID()
	})
}

// Exec executes the query.
func (u *PermissionApiResourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PermissionApiResourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PermissionApiResourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PermissionApiResourceUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PermissionApiResourceUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PermissionApiResourceCreateBulk is the builder for creating many PermissionApiResource entities in bulk.
type PermissionApiResourceCreateBulk struct {
	config
	err      error
	builders []*PermissionApiResourceCreate
	conflict []sql.ConflictOption
}

// Save creates the PermissionApiResource entities in the database.
func (_c *PermissionApiResourceCreateBulk) Save(ctx context.Context) ([]*PermissionApiResource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PermissionApiResource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionApiResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PermissionApiResourceCreateBulk) SaveX(ctx context.Context) []*PermissionApiResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionApiResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionApiResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PermissionApiResource.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PermissionApiResourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PermissionApiResourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *PermissionApiResourceUpsertBulk {
	_c.conflict = opts
	return &PermissionApiResourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PermissionApiResource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PermissionApiResourceCreateBulk) OnConflictColumns(columns ...string) *PermissionApiResourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PermissionApiResourceUpsertBulk{
		create: _c,
	}
}

// PermissionApiResourceUpsertBulk is the builder for "upsert"-ing
// a bulk of PermissionApiResource nodes.
type PermissionApiResourceUpsertBulk struct {
	create *PermissionApiResourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PermissionApiResource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(permissionapiresource.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PermissionApiResourceUpsertBulk) UpdateNewValues() *PermissionApiResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(permissionapiresource.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(permissionapiresource.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(permissionapiresource.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PermissionApiResource.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PermissionApiResourceUpsertBulk) Ignore() *PermissionApiResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PermissionApiResourceUpsertBulk) DoNothing() *PermissionApiResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PermissionApiResourceCreateBulk.OnConflict
// documentation for more info.
func (u *PermissionApiResourceUpsertBulk) Update(set func(*PermissionApiResourceUpsert)) *PermissionApiResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PermissionApiResourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PermissionApiResourceUpsertBulk) SetUpdatedAt(v time.Time) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertBulk) UpdateUpdatedAt() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *PermissionApiResourceUpsertBulk) ClearUpdatedAt() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PermissionApiResourceUpsertBulk) SetDeletedAt(v time.Time) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertBulk) UpdateDeletedAt() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PermissionApiResourceUpsertBulk) ClearDeletedAt() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *PermissionApiResourceUpsertBulk) SetCreatedBy(v uint32) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *PermissionApiResourceUpsertBulk) AddCreatedBy(v uint32) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertBulk) UpdateCreatedBy() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *PermissionApiResourceUpsertBulk) ClearCreatedBy() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PermissionApiResourceUpsertBulk) SetUpdatedBy(v uint32) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PermissionApiResourceUpsertBulk) AddUpdatedBy(v uint32) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertBulk) UpdateUpdatedBy() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PermissionApiResourceUpsertBulk) ClearUpdatedBy() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *PermissionApiResourceUpsertBulk) SetDeletedBy(v uint32) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *PermissionApiResourceUpsertBulk) AddDeletedBy(v uint32) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertBulk) UpdateDeletedBy() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *PermissionApiResourceUpsertBulk) ClearDeletedBy() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.ClearDeletedBy()
	})
}

// SetPermissionID sets the "permission_id" field.
func (u *PermissionApiResourceUpsertBulk) SetPermissionID(v uint32) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetPermissionID(v)
	})
}

// AddPermissionID adds v to the "permission_id" field.
func (u *PermissionApiResourceUpsertBulk) AddPermissionID(v uint32) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.AddPermissionID(v)
	})
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertBulk) UpdatePermissionID() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdatePermissionID()
	})
}

// SetAPIResourceID sets the "api_resource_id" field.
func (u *PermissionApiResourceUpsertBulk) SetAPIResourceID(v uint32) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.SetAPIResourceID(v)
	})
}

// AddAPIResourceID adds v to the "api_resource_id" field.
func (u *PermissionApiResourceUpsertBulk) AddAPIResourceID(v uint32) *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.AddAPIResourceID(v)
	})
}

// UpdateAPIResourceID sets the "api_resource_id" field to the value that was provided on create.
func (u *PermissionApiResourceUpsertBulk) UpdateAPIResourceID() *PermissionApiResourceUpsertBulk {
	return u.Update(func(s *PermissionApiResourceUpsert) {
		s.UpdateAPIResourceID()
	})
}

// Exec executes the query.
func (u *PermissionApiResourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PermissionApiResourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PermissionApiResourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PermissionApiResourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
