// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/permissionapiresource"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PermissionApiResourceUpdate is the builder for updating PermissionApiResource entities.
type PermissionApiResourceUpdate struct {
	config
	hooks     []Hook
	mutation  *PermissionApiResourceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PermissionApiResourceUpdate builder.
func (_u *PermissionApiResourceUpdate) Where(ps ...predicate.PermissionApiResource) *PermissionApiResourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PermissionApiResourceUpdate) SetUpdatedAt(v time.Time) *PermissionApiResourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PermissionApiResourceUpdate) SetNillableUpdatedAt(v *time.Time) *PermissionApiResourceUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *PermissionApiResourceUpdate) ClearUpdatedAt() *PermissionApiResourceUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PermissionApiResourceUpdate) SetDeletedAt(v time.Time) *PermissionApiResourceUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PermissionApiResourceUpdate) SetNillableDeletedAt(v *time.Time) *PermissionApiResourceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PermissionApiResourceUpdate) ClearDeletedAt() *PermissionApiResourceUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PermissionApiResourceUpdate) SetCreatedBy(v uint32) *PermissionApiResourceUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PermissionApiResourceUpdate) SetNillableCreatedBy(v *uint32) *PermissionApiResourceUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PermissionApiResourceUpdate) AddCreatedBy(v int32) *PermissionApiResourceUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PermissionApiResourceUpdate) ClearCreatedBy() *PermissionApiResourceUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PermissionApiResourceUpdate) SetUpdatedBy(v uint32) *PermissionApiResourceUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PermissionApiResourceUpdate) SetNillableUpdatedBy(v *uint32) *PermissionApiResourceUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *PermissionApiResourceUpdate) AddUpdatedBy(v int32) *PermissionApiResourceUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PermissionApiResourceUpdate) ClearUpdatedBy() *PermissionApiResourceUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *PermissionApiResourceUpdate) SetDeletedBy(v uint32) *PermissionApiResourceUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *PermissionApiResourceUpdate) SetNillableDeletedBy(v *uint32) *PermissionApiResourceUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *PermissionApiResourceUpdate) AddDeletedBy(v int32) *PermissionApiResourceUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *PermissionApiResourceUpdate) ClearDeletedBy() *PermissionApiResourceUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *PermissionApiResourceUpdate) SetPermissionID(v uint32) *PermissionApiResourceUpdate {
	_u.mutation.ResetPermissionID()
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *PermissionApiResourceUpdate) SetNillablePermissionID(v *uint32) *PermissionApiResourceUpdate {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// AddPermissionID adds value to the "permission_id" field.
func (_u *PermissionApiResourceUpdate) AddPermissionID(v int32) *PermissionApiResourceUpdate {
	_u.mutation.AddPermissionID(v)
	return _u
}

// SetAPIResourceID sets the "api_resource_id" field.
func (_u *PermissionApiResourceUpdate) SetAPIResourceID(v uint32) *PermissionApiResourceUpdate {
	_u.mutation.ResetAPIResourceID()
	_u.mutation.SetAPIResourceID(v)
	return _u
}

// SetNillableAPIResourceID sets the "api_resource_id" field if the given value is not nil.
func (_u *PermissionApiResourceUpdate) SetNillableAPIResourceID(v *uint32) *PermissionApiResourceUpdate {
	if v != nil {
		_u.SetAPIResourceID(*v)
	}
	return _u
}

// AddAPIResourceID adds value to the "api_resource_id" field.
func (_u *PermissionApiResourceUpdate) AddAPIResourceID(v int32) *PermissionApiResourceUpdate {
	_u.mutation.AddAPIResourceID(v)
	return _u
}

// Mutation returns the PermissionApiResourceMutation object of the builder.
func (_u *PermissionApiResourceUpdate) Mutation() *PermissionApiResourceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PermissionApiResourceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionApiResourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PermissionApiResourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionApiResourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PermissionApiResourceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PermissionApiResourceUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PermissionApiResourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(permissionapiresource.Table, permissionapiresource.Columns, sqlgraph.NewFieldSpec(permissionapiresource.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(permissionapiresource.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(permissionapiresource.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(permissionapiresource.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(permissionapiresource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(permissionapiresource.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(permissionapiresource.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(permissionapiresource.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(permissionapiresource.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(permissionapiresource.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(permissionapiresource.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(permissionapiresource.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(permissionapiresource.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(permissionapiresource.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(permissionapiresource.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(permissionapiresource.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PermissionID(); ok {
		_spec.SetField(permissionapiresource.FieldPermissionID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPermissionID(); ok {
		_spec.AddField(permissionapiresource.FieldPermissionID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.APIResourceID(); ok {
		_spec.SetField(permissionapiresource.FieldAPIResourceID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAPIResourceID(); ok {
		_spec.AddField(permissionapiresource.FieldAPIResourceID, field.TypeUint32, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permissionapiresource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PermissionApiResourceUpdateOne is the builder for updating a single PermissionApiResource entity.
type PermissionApiResourceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PermissionApiResourceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PermissionApiResourceUpdateOne) SetUpdatedAt(v time.Time) *PermissionApiResourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PermissionApiResourceUpdateOne) SetNillableUpdatedAt(v *time.Time) *PermissionApiResourceUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *PermissionApiResourceUpdateOne) ClearUpdatedAt() *PermissionApiResourceUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PermissionApiResourceUpdateOne) SetDeletedAt(v time.Time) *PermissionApiResourceUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PermissionApiResourceUpdateOne) SetNillableDeletedAt(v *time.Time) *PermissionApiResourceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PermissionApiResourceUpdateOne) ClearDeletedAt() *PermissionApiResourceUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PermissionApiResourceUpdateOne) SetCreatedBy(v uint32) *PermissionApiResourceUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PermissionApiResourceUpdateOne) SetNillableCreatedBy(v *uint32) *PermissionApiResourceUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PermissionApiResourceUpdateOne) AddCreatedBy(v int32) *PermissionApiResourceUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PermissionApiResourceUpdateOne) ClearCreatedBy() *PermissionApiResourceUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PermissionApiResourceUpdateOne) SetUpdatedBy(v uint32) *PermissionApiResourceUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PermissionApiResourceUpdateOne) SetNillableUpdatedBy(v *uint32) *PermissionApiResourceUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *PermissionApiResourceUpdateOne) AddUpdatedBy(v int32) *PermissionApiResourceUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PermissionApiResourceUpdateOne) ClearUpdatedBy() *PermissionApiResourceUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *PermissionApiResourceUpdateOne) SetDeletedBy(v uint32) *PermissionApiResourceUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *PermissionApiResourceUpdateOne) SetNillableDeletedBy(v *uint32) *PermissionApiResourceUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *PermissionApiResourceUpdateOne) AddDeletedBy(v int32) *PermissionApiResourceUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *PermissionApiResourceUpdateOne) ClearDeletedBy() *PermissionApiResourceUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *PermissionApiResourceUpdateOne) SetPermissionID(v uint32) *PermissionApiResourceUpdateOne {
	_u.mutation.ResetPermissionID()
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *PermissionApiResourceUpdateOne) SetNillablePermissionID(v *uint32) *PermissionApiResourceUpdateOne {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// AddPermissionID adds value to the "permission_id" field.
func (_u *PermissionApiResourceUpdateOne) AddPermissionID(v int32) *PermissionApiResourceUpdateOne {
	_u.mutation.AddPermissionID(v)
	return _u
}

// SetAPIResourceID sets the "api_resource_id" field.
func (_u *PermissionApiResourceUpdateOne) SetAPIResourceID(v uint32) *PermissionApiResourceUpdateOne {
	_u.mutation.ResetAPIResourceID()
	_u.mutation.SetAPIResourceID(v)
	return _u
}

// SetNillableAPIResourceID sets the "api_resource_id" field if the given value is not nil.
func (_u *PermissionApiResourceUpdateOne) SetNillableAPIResourceID(v *uint32) *PermissionApiResourceUpdateOne {
	if v != nil {
		_u.SetAPIResourceID(*v)
	}
	return _u
}

// AddAPIResourceID adds value to the "api_resource_id" field.
func (_u *PermissionApiResourceUpdateOne) AddAPIResourceID(v int32) *PermissionApiResourceUpdateOne {
	_u.mutation.AddAPIResourceID(v)
	return _u
}

// Mutation returns the PermissionApiResourceMutation object of the builder.
func (_u *PermissionApiResourceUpdateOne) Mutation() *PermissionApiResourceMutation {
	return _u.mutation
}

// Where appends a list predicates to the PermissionApiResourceUpdate builder.
func (_u *PermissionApiResourceUpdateOne) Where(ps ...predicate.PermissionApiResource) *PermissionApiResourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PermissionApiResourceUpdateOne) Select(field string, fields ...string) *PermissionApiResourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PermissionApiResource entity.
func (_u *PermissionApiResourceUpdateOne) Save(ctx context.Context) (*PermissionApiResource, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionApiResourceUpdateOne) SaveX(ctx context.Context) *PermissionApiResource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PermissionApiResourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionApiResourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PermissionApiResourceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PermissionApiResourceUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PermissionApiResourceUpdateOne) sqlSave(ctx context.Context) (_node *PermissionApiResource, err error) {
	_spec := sqlgraph.NewUpdateSpec(permissionapiresource.Table, permissionapiresource.Columns, sqlgraph.NewFieldSpec(permissionapiresource.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PermissionApiResource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, permissionapiresource.FieldID)
		for _, f := range fields {
			if !permissionapiresource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != permissionapiresource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(permissionapiresource.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(permissionapiresource.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(permissionapiresource.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(permissionapiresource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(permissionapiresource.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(permissionapiresource.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(permissionapiresource.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(permissionapiresource.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(permissionapiresource.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(permissionapiresource.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(permissionapiresource.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(permissionapiresource.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(permissionapiresource.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(permissionapiresource.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(permissionapiresource.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PermissionID(); ok {
		_spec.SetField(permissionapiresource.FieldPermissionID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPermissionID(); ok {
		_spec.AddField(permissionapiresource.FieldPermissionID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.APIResourceID(); ok {
		_spec.SetField(permissionapiresource.FieldAPIResourceID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAPIResourceID(); ok {
		_spec.AddField(permissionapiresource.FieldAPIResourceID, field.TypeUint32, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &PermissionApiResource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permissionapiresource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
