// Code generated by ent, DO NOT EDIT.

package permissionapiresource

import (
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldDeletedBy, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldTenantID, v))
}

// PermissionID applies equality check predicate on the "permission_id" field. It's identical to PermissionIDEQ.
func PermissionID(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldPermissionID, v))
}

// APIResourceID applies equality check predicate on the "api_resource_id" field. It's identical to APIResourceIDEQ.
func APIResourceID(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldAPIResourceID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotNull(FieldDeletedBy))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotNull(FieldTenantID))
}

// PermissionIDEQ applies the EQ predicate on the "permission_id" field.
func PermissionIDEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldPermissionID, v))
}

// PermissionIDNEQ applies the NEQ predicate on the "permission_id" field.
func PermissionIDNEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNEQ(FieldPermissionID, v))
}

// PermissionIDIn applies the In predicate on the "permission_id" field.
func PermissionIDIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIn(FieldPermissionID, vs...))
}

// PermissionIDNotIn applies the NotIn predicate on the "permission_id" field.
func PermissionIDNotIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotIn(FieldPermissionID, vs...))
}

// PermissionIDGT applies the GT predicate on the "permission_id" field.
func PermissionIDGT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGT(FieldPermissionID, v))
}

// PermissionIDGTE applies the GTE predicate on the "permission_id" field.
func PermissionIDGTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGTE(FieldPermissionID, v))
}

// PermissionIDLT applies the LT predicate on the "permission_id" field.
func PermissionIDLT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLT(FieldPermissionID, v))
}

// PermissionIDLTE applies the LTE predicate on the "permission_id" field.
func PermissionIDLTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLTE(FieldPermissionID, v))
}

// APIResourceIDEQ applies the EQ predicate on the "api_resource_id" field.
func APIResourceIDEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldEQ(FieldAPIResourceID, v))
}

// APIResourceIDNEQ applies the NEQ predicate on the "api_resource_id" field.
func APIResourceIDNEQ(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNEQ(FieldAPIResourceID, v))
}

// APIResourceIDIn applies the In predicate on the "api_resource_id" field.
func APIResourceIDIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldIn(FieldAPIResourceID, vs...))
}

// APIResourceIDNotIn applies the NotIn predicate on the "api_resource_id" field.
func APIResourceIDNotIn(vs ...uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldNotIn(FieldAPIResourceID, vs...))
}

// APIResourceIDGT applies the GT predicate on the "api_resource_id" field.
func APIResourceIDGT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGT(FieldAPIResourceID, v))
}

// APIResourceIDGTE applies the GTE predicate on the "api_resource_id" field.
func APIResourceIDGTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldGTE(FieldAPIResourceID, v))
}

// APIResourceIDLT applies the LT predicate on the "api_resource_id" field.
func APIResourceIDLT(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLT(FieldAPIResourceID, v))
}

// APIResourceIDLTE applies the LTE predicate on the "api_resource_id" field.
func APIResourceIDLTE(v uint32) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.FieldLTE(FieldAPIResourceID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PermissionApiResource) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PermissionApiResource) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PermissionApiResource) predicate.PermissionApiResource {
	return predicate.PermissionApiResource(sql.NotPredicates(p))
}
