// Code generated by ent, DO NOT EDIT.

package notificationdelivery

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the notificationdelivery type in the database.
	Label = "notification_delivery"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldRecipientUserID holds the string denoting the recipient_user_id field in the database.
	FieldRecipientUserID = "recipient_user_id"
	// FieldRelatedID holds the string denoting the related_id field in the database.
	FieldRelatedID = "related_id"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldSentAt holds the string denoting the sent_at field in the database.
	FieldSentAt = "sent_at"
	// Table holds the table name of the notificationdelivery in the database.
	Table = "sys_notification_deliveries"
)

// Columns holds all SQL columns for notificationdelivery fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldEventType,
	FieldChannel,
	FieldChannelID,
	FieldRecipientUserID,
	FieldRelatedID,
	FieldTarget,
	FieldStatus,
	FieldLastError,
	FieldRequestID,
	FieldAttempts,
	FieldSentAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts uint32
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// EventType defines the type for the "event_type" enum field.
type EventType string

// EventType values.
const (
	EventTypePasswordResetCode EventType = "PASSWORD_RESET_CODE"
	EventTypeContactBindCode   EventType = "CONTACT_BIND_CODE"
	EventTypeChannelTestEmail  EventType = "CHANNEL_TEST_EMAIL"
	EventTypeInternalMessage   EventType = "INTERNAL_MESSAGE"
)

func (et EventType) String() string {
	return string(et)
}

// EventTypeValidator is a validator for the "event_type" field enum values. It is called by the builders before save.
func EventTypeValidator(et EventType) error {
	switch et {
	case EventTypePasswordResetCode, EventTypeContactBindCode, EventTypeChannelTestEmail, EventTypeInternalMessage:
		return nil
	default:
		return fmt.Errorf("notificationdelivery: invalid enum value for event_type field: %q", et)
	}
}

// Channel defines the type for the "channel" enum field.
type Channel string

// Channel values.
const (
	ChannelEmail    Channel = "EMAIL"
	ChannelSms      Channel = "SMS"
	ChannelWebhook  Channel = "WEBHOOK"
	ChannelInternal Channel = "INTERNAL"
)

func (c Channel) String() string {
	return string(c)
}

// ChannelValidator is a validator for the "channel" field enum values. It is called by the builders before save.
func ChannelValidator(c Channel) error {
	switch c {
	case ChannelEmail, ChannelSms, ChannelWebhook, ChannelInternal:
		return nil
	default:
		return fmt.Errorf("notificationdelivery: invalid enum value for channel field: %q", c)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusSending is the default value of the Status enum.
const DefaultStatus = StatusSending

// Status values.
const (
	StatusSending Status = "SENDING"
	StatusSent    Status = "SENT"
	StatusFailed  Status = "FAILED"
	StatusSkipped Status = "SKIPPED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusSending, StatusSent, StatusFailed, StatusSkipped:
		return nil
	default:
		return fmt.Errorf("notificationdelivery: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the NotificationDelivery queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByRecipientUserID orders the results by the recipient_user_id field.
func ByRecipientUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipientUserID, opts...).ToFunc()
}

// ByRelatedID orders the results by the related_id field.
func ByRelatedID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelatedID, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// BySentAt orders the results by the sent_at field.
func BySentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSentAt, opts...).ToFunc()
}
